/**********************************************************************
 Name: {{api_name}}
 Other classes used:
======================================================
Description: 
	Sample description
***********************************************************************/
global class {{ api_name }} implements Schedulable 
{
	global void execute(SchedulableContext sc) 
	{
		//MyBatchClass b = new MyBatchClass();
		//database.executebatch(b);
	}
}