/**********************************************************************
 Name: {{api_name}}
 Other classes used:
======================================================
Description: 
	Sample description
======================================================
History                                                            
-------                                                            
VERSION         AUTHOR                  DATE            DETAIL                                 
1.0             John Doe  				29/08/1997		Initial development
***********************************************************************/

@isTest
private class {{ api_name }} 
{	
	@testSetup
    static void createTestData() 
	{
		// Set up test data for test methods
	}
	
	static testMethod void test_method_one() 
	{
		// Implement test code
	}	
}