/**********************************************************************
 Name: {{api_name}}
 Other classes used:
======================================================
Description: 
	Sample description
======================================================
History                                                            
-------                                                            
VERSION         AUTHOR                  DATE            DETAIL                                 
1.0             John Doe  				29/08/1997		Initial development
***********************************************************************/
global class {{ api_name }} implements Schedulable 
{
	global void execute(SchedulableContext sc) 
	{
		//MyBatchClass b = new MyBatchClass();
		//database.executebatch(b);
	}
}