/**********************************************************************
 Name: {{api_name}}
 Other classes used:
======================================================
Description: 
	Sample description
***********************************************************************/
public with sharing class {{ api_name }} 
{
	/*public static ccQueryResult getServiceOverview()
	{			
		ccServiceOrdersSelector serviceOrderSelector = new ccServiceOrdersSelector();
		List<Schema.SObjectField> returnFields = new List<Schema.SObjectField> {
				Service_Order__c.Id,
				Service_Order__c.Name
			};
		serviceOrderSelector.sObjectFieldList = returnFields;
		serviceOrderSelector.paging.enabled = false;
		return serviceOrderSelector.selectAll();
	}*/
}